FROM node:20-alpine AS base

WORKDIR /app

# Dependency layer
COPY package.json package-lock.json ./
RUN npm ci

# Build layer
COPY . .
RUN npm run build

# Production runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=base /app/public ./public
COPY --from=base /app/.next/standalone ./
COPY --from=base /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
