# Generated by Django 6.0.4 on 2026-04-11 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('template_id', models.CharField(choices=[('minimal', 'Minimal'), ('professional', 'Professional'), ('modern', 'Modern'), ('creative', 'Creative'), ('academic', 'Academic')], default='minimal', max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('ai_content', models.JSONField(blank=True, default=dict, null=True)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Ruscha'), ('en', 'Inglizcha')], default='uz', max_length=5)),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rezume',
                'verbose_name_plural': 'Rezumeler',
                'db_table': 'resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
